### ISSUE TITLE
Evaluation error

### ISSUE THREAD

**Issue by ziyouzheilu** [zwq456/CLIP-VIS#4]
When I run evaluation script:sh scripts/eval_video.sh configs/clipvis_video_ConvNeXt-B.yaml 1 '("lvvis_val",)' 1196 output/lvvis models/clipvis_lvis_base_7_re.pth MODEL.MASK_FORMER.DEC_LAYERS 7.It appears the error:
[12/29 09:29:11 d2.evaluation.evaluator]: Start inference on 837 batches
Traceback (most recent call last):
  File "train_net_video.py", line 301, in <module>
    launch(
  File "/root/autodl-tmp/detectron2/detectron2/engine/launch.py", line 84, in launch
    main_func(*args)
  File "train_net_video.py", line 286, in main
    res = Trainer.test(cfg, model)
  File "train_net_video.py", line 244, in test
    results_i = inference_on_dataset(model, data_loader, evaluator)
  File "/root/autodl-tmp/detectron2/detectron2/evaluation/evaluator.py", line 165, in inference_on_dataset
    outputs = model(inputs)
  File "/root/miniconda3/envs/clipvis/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/root/autodl-tmp/CLIP-VIS/clipvis/clipvis_video.py", line 328, in forward
    text_classifier, num_templates = self.get_text_classifier()
  File "/root/autodl-tmp/CLIP-VIS/clipvis/clipvis_video.py", line 205, in get_text_classifier
    text_classifier.append(self.backbone.get_text_classifier(self.test_class_names[idx:idx+bs], self.device).detach())
  File "/root/autodl-tmp/CLIP-VIS/clipvis/modeling/backbone/clip.py", line 221, in get_text_classifier
    text_features = self.encode_text(text_tokens, normalize=False)
  File "/root/autodl-tmp/CLIP-VIS/clipvis/modeling/backbone/clip.py", line 102, in encode_text
    x = self.clip_model.transformer(x, attn_mask=self.clip_model.attn_mask)
  File "/root/miniconda3/envs/clipvis/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/root/miniconda3/envs/clipvis/lib/python3.8/site-packages/open_clip/transformer.py", line 363, in forward
    x = r(x, attn_mask=attn_mask)
  File "/root/miniconda3/envs/clipvis/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/root/miniconda3/envs/clipvis/lib/python3.8/site-packages/open_clip/transformer.py", line 263, in forward
    x = q_x + self.ls_1(self.attention(q_x=self.ln_1(q_x), k_x=k_x, v_x=v_x, attn_mask=attn_mask))
  File "/root/miniconda3/envs/clipvis/lib/python3.8/site-packages/open_clip/transformer.py", line 250, in attention
    return self.attn(
  File "/root/miniconda3/envs/clipvis/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/root/miniconda3/envs/clipvis/lib/python3.8/site-packages/torch/nn/modules/activation.py", line 1113, in forward
    return torch._native_multi_head_attention(
RuntimeError: Mask shape should match input

**Comment by zwq456** [comment]
Please check the version of `open-clip-torch` and try updating it to version 2.24.0.
`pip install open-clip-torch==2.24.0`
